Repository openshift/cluster-api-provider-kubevirt, pull requests merged in 2020-12, with the labels that each got.

#20 Add providerID controller
  cmd/manager/main.go
  pkg/managers/vm/machine_scope.go
  pkg/managers/vm/vm_test.go
  pkg/providerid/controller.go
Labels: approved, lgtm

#22 Fix providerID + move infraClusterClient initialize to main
  cmd/manager/main.go
  pkg/clients/infracluster/client.go
  pkg/managers/vm/machine_scope.go
  pkg/managers/vm/stubs_test.go
  pkg/managers/vm/vm.go
  pkg/managers/vm/vm_test.go
  pkg/providerid/controller.go
Labels: approved, lgtm

#24 Bug 1908654: Fix volumes and disks (inside the VM) names to short name
  pkg/managers/vm/machine_scope.go
  pkg/managers/vm/stubs_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25 Bug 1910783: Set termination_grace_period_seconds to 10 minutes
  pkg/managers/vm/machine_scope.go
  pkg/managers/vm/stubs_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
